--- 
- hosts: all 
  become: yes
  tasks: 
  - name: install java on ubuntu
    apt: 
      name: openjdk-8-jdk
      state: present
  - name: install java on redhat
    yum:
      name: java-1.8.0-openjdk
      state: present