--- 
- hosts: 172.31.35.15 
  become: yes 
  tasks:
  - name: execute linux command
    command: hostname -f 
    register: myresult 
  - name: i want to display my result 
    debug: 
      msg: "{{myresult}}"
  