--- 
- hosts: 172.31.35.15 
  become: yes
  tasks:
  - name: install git 
    apt: 
      name: git 
      state: present
  - name: install apacje2
    apt: 
      name: apache
      state: present 
  - name: install wget 
    apt:
      name: wget 
      state: present 