--- 
- hosts: 172.31.35.15 
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install apache2
    apt: 
      name: apache2
      state: present
  - name: copy file into another file 
    copy:
      src: staticfile.txt
      dest: /home/ubuntu/mystaticfile.txt