--- 
- hosts: 172.31.35.15 
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install apache2
    apt: 
      name: apache2
      state: present
  - name: copy file into another file 
    copy:
      src: staticfile.txt
      dest: /home/ubuntu/mystaticfile.txt
  - name: copy index.j2 file into ansible node side 
    template:
      src: myindex.j2
      dest: /var/www/html/index.html
  - name: downloading internet files
    ansible.builtin.get_url:
      url: https://www.digitalocean.com/community/tutorials/how-to-install-jenkins-on-ubuntu-18-04
      dest: /home/ubuntu/jenkins.war
    force_basic_path: true